option to have default values for primitive record fields
UbiqueInnovation/djinni pull request #15
Opened 2023-11-13 13:54 UTC by fbzli

2023-11-13 13:56 UTC, M-Wong requested changes

2023-11-13 13:56 UTC, M-Wong commented on src/source/KotlinGenerator.scala
> +          w.w(s"var ${idJava.field(f.ident)}: $fieldType")
Können wir die Data Class Fields `val` machen?

2023-11-13 14:00 UTC, fbzli commented on src/source/KotlinGenerator.scala
> +          w.w(s"var ${idJava.field(f.ident)}: $fieldType")
habe ich mir auch überlegt, spricht nichts dagegen? (ausser dass die Java Fields auch nicht final waren)

2023-11-13 15:50 UTC, M-Wong commented on src/source/KotlinGenerator.scala
> +          w.w(s"var ${idJava.field(f.ident)}: $fieldType")
Wenns irgendwo Code kaputt macht dann war der Code meiner Meinung nach eh schon falsch 😄

2023-11-14 05:53 UTC, maurhofer-ubique approved these changes

2023-11-14 07:07 UTC, M-Wong approved these changes

2023-11-14 13:05 UTC, merged